### ISSUE TITLE
Finish Core Level Game Loop

### ISSUE THREAD

**Issue by MashdorDev** [MashdorDev/unbread#101]
# what
We need to finish the core-level game loop. 

Currently, we start the level with a middle; however, there is no end; we need to add a win condition and a lose condition to the story itself, as and when a player loses all health trigger lose condition.

# Todos
- [ ] Add a win condition to the level
- [ ] add a lose condition to the level
- [ ] test the level from beginning to end.
